// Code generated by ent, DO NOT EDIT.

package uploadedcontent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ent-join/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.UploadedContent {
	return predicate.UploadedContent(sql.FieldContainsFold(FieldID, id))
}

// HasContents applies the HasEdge predicate on the "contents" edge.
func HasContents() predicate.UploadedContent {
	return predicate.UploadedContent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContentsTable, ContentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentsWith applies the HasEdge predicate on the "contents" edge with a given conditions (other predicates).
func HasContentsWith(preds ...predicate.Content) predicate.UploadedContent {
	return predicate.UploadedContent(func(s *sql.Selector) {
		step := newContentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UploadedContent) predicate.UploadedContent {
	return predicate.UploadedContent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UploadedContent) predicate.UploadedContent {
	return predicate.UploadedContent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UploadedContent) predicate.UploadedContent {
	return predicate.UploadedContent(sql.NotPredicates(p))
}
