// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ent-join/ent/content"
	"github.com/ent-join/ent/contentmoviemetadata"
	"github.com/ent-join/ent/schema"
	"github.com/ent-join/ent/uploadedcontent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contentFields := schema.Content{}.Fields()
	_ = contentFields
	// contentDescID is the schema descriptor for id field.
	contentDescID := contentFields[0].Descriptor()
	// content.IDValidator is a validator for the "id" field. It is called by the builders before save.
	content.IDValidator = contentDescID.Validators[0].(func(string) error)
	contentmoviemetadataFields := schema.ContentMovieMetadata{}.Fields()
	_ = contentmoviemetadataFields
	// contentmoviemetadataDescID is the schema descriptor for id field.
	contentmoviemetadataDescID := contentmoviemetadataFields[0].Descriptor()
	// contentmoviemetadata.IDValidator is a validator for the "id" field. It is called by the builders before save.
	contentmoviemetadata.IDValidator = contentmoviemetadataDescID.Validators[0].(func(string) error)
	uploadedcontentFields := schema.UploadedContent{}.Fields()
	_ = uploadedcontentFields
	// uploadedcontentDescID is the schema descriptor for id field.
	uploadedcontentDescID := uploadedcontentFields[0].Descriptor()
	// uploadedcontent.IDValidator is a validator for the "id" field. It is called by the builders before save.
	uploadedcontent.IDValidator = uploadedcontentDescID.Validators[0].(func(string) error)
}
