// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ent-join/ent/content"
	"github.com/ent-join/ent/predicate"
	"github.com/ent-join/ent/uploadedcontent"
)

// UploadedContentQuery is the builder for querying UploadedContent entities.
type UploadedContentQuery struct {
	config
	ctx          *QueryContext
	order        []uploadedcontent.OrderOption
	inters       []Interceptor
	predicates   []predicate.UploadedContent
	withContents *ContentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UploadedContentQuery builder.
func (ucq *UploadedContentQuery) Where(ps ...predicate.UploadedContent) *UploadedContentQuery {
	ucq.predicates = append(ucq.predicates, ps...)
	return ucq
}

// Limit the number of records to be returned by this query.
func (ucq *UploadedContentQuery) Limit(limit int) *UploadedContentQuery {
	ucq.ctx.Limit = &limit
	return ucq
}

// Offset to start from.
func (ucq *UploadedContentQuery) Offset(offset int) *UploadedContentQuery {
	ucq.ctx.Offset = &offset
	return ucq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ucq *UploadedContentQuery) Unique(unique bool) *UploadedContentQuery {
	ucq.ctx.Unique = &unique
	return ucq
}

// Order specifies how the records should be ordered.
func (ucq *UploadedContentQuery) Order(o ...uploadedcontent.OrderOption) *UploadedContentQuery {
	ucq.order = append(ucq.order, o...)
	return ucq
}

// QueryContents chains the current query on the "contents" edge.
func (ucq *UploadedContentQuery) QueryContents() *ContentQuery {
	query := (&ContentClient{config: ucq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ucq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uploadedcontent.Table, uploadedcontent.FieldID, selector),
			sqlgraph.To(content.Table, content.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, uploadedcontent.ContentsTable, uploadedcontent.ContentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(ucq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UploadedContent entity from the query.
// Returns a *NotFoundError when no UploadedContent was found.
func (ucq *UploadedContentQuery) First(ctx context.Context) (*UploadedContent, error) {
	nodes, err := ucq.Limit(1).All(setContextOp(ctx, ucq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uploadedcontent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ucq *UploadedContentQuery) FirstX(ctx context.Context) *UploadedContent {
	node, err := ucq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UploadedContent ID from the query.
// Returns a *NotFoundError when no UploadedContent ID was found.
func (ucq *UploadedContentQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ucq.Limit(1).IDs(setContextOp(ctx, ucq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{uploadedcontent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ucq *UploadedContentQuery) FirstIDX(ctx context.Context) string {
	id, err := ucq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UploadedContent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UploadedContent entity is found.
// Returns a *NotFoundError when no UploadedContent entities are found.
func (ucq *UploadedContentQuery) Only(ctx context.Context) (*UploadedContent, error) {
	nodes, err := ucq.Limit(2).All(setContextOp(ctx, ucq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uploadedcontent.Label}
	default:
		return nil, &NotSingularError{uploadedcontent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ucq *UploadedContentQuery) OnlyX(ctx context.Context) *UploadedContent {
	node, err := ucq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UploadedContent ID in the query.
// Returns a *NotSingularError when more than one UploadedContent ID is found.
// Returns a *NotFoundError when no entities are found.
func (ucq *UploadedContentQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ucq.Limit(2).IDs(setContextOp(ctx, ucq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{uploadedcontent.Label}
	default:
		err = &NotSingularError{uploadedcontent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ucq *UploadedContentQuery) OnlyIDX(ctx context.Context) string {
	id, err := ucq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UploadedContents.
func (ucq *UploadedContentQuery) All(ctx context.Context) ([]*UploadedContent, error) {
	ctx = setContextOp(ctx, ucq.ctx, "All")
	if err := ucq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UploadedContent, *UploadedContentQuery]()
	return withInterceptors[[]*UploadedContent](ctx, ucq, qr, ucq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ucq *UploadedContentQuery) AllX(ctx context.Context) []*UploadedContent {
	nodes, err := ucq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UploadedContent IDs.
func (ucq *UploadedContentQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ucq.ctx.Unique == nil && ucq.path != nil {
		ucq.Unique(true)
	}
	ctx = setContextOp(ctx, ucq.ctx, "IDs")
	if err = ucq.Select(uploadedcontent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ucq *UploadedContentQuery) IDsX(ctx context.Context) []string {
	ids, err := ucq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ucq *UploadedContentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ucq.ctx, "Count")
	if err := ucq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ucq, querierCount[*UploadedContentQuery](), ucq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ucq *UploadedContentQuery) CountX(ctx context.Context) int {
	count, err := ucq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ucq *UploadedContentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ucq.ctx, "Exist")
	switch _, err := ucq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ucq *UploadedContentQuery) ExistX(ctx context.Context) bool {
	exist, err := ucq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UploadedContentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ucq *UploadedContentQuery) Clone() *UploadedContentQuery {
	if ucq == nil {
		return nil
	}
	return &UploadedContentQuery{
		config:       ucq.config,
		ctx:          ucq.ctx.Clone(),
		order:        append([]uploadedcontent.OrderOption{}, ucq.order...),
		inters:       append([]Interceptor{}, ucq.inters...),
		predicates:   append([]predicate.UploadedContent{}, ucq.predicates...),
		withContents: ucq.withContents.Clone(),
		// clone intermediate query.
		sql:  ucq.sql.Clone(),
		path: ucq.path,
	}
}

// WithContents tells the query-builder to eager-load the nodes that are connected to
// the "contents" edge. The optional arguments are used to configure the query builder of the edge.
func (ucq *UploadedContentQuery) WithContents(opts ...func(*ContentQuery)) *UploadedContentQuery {
	query := (&ContentClient{config: ucq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ucq.withContents = query
	return ucq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (ucq *UploadedContentQuery) GroupBy(field string, fields ...string) *UploadedContentGroupBy {
	ucq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UploadedContentGroupBy{build: ucq}
	grbuild.flds = &ucq.ctx.Fields
	grbuild.label = uploadedcontent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (ucq *UploadedContentQuery) Select(fields ...string) *UploadedContentSelect {
	ucq.ctx.Fields = append(ucq.ctx.Fields, fields...)
	sbuild := &UploadedContentSelect{UploadedContentQuery: ucq}
	sbuild.label = uploadedcontent.Label
	sbuild.flds, sbuild.scan = &ucq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UploadedContentSelect configured with the given aggregations.
func (ucq *UploadedContentQuery) Aggregate(fns ...AggregateFunc) *UploadedContentSelect {
	return ucq.Select().Aggregate(fns...)
}

func (ucq *UploadedContentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ucq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ucq); err != nil {
				return err
			}
		}
	}
	for _, f := range ucq.ctx.Fields {
		if !uploadedcontent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ucq.path != nil {
		prev, err := ucq.path(ctx)
		if err != nil {
			return err
		}
		ucq.sql = prev
	}
	return nil
}

func (ucq *UploadedContentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UploadedContent, error) {
	var (
		nodes       = []*UploadedContent{}
		_spec       = ucq.querySpec()
		loadedTypes = [1]bool{
			ucq.withContents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UploadedContent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UploadedContent{config: ucq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ucq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ucq.withContents; query != nil {
		if err := ucq.loadContents(ctx, query, nodes,
			func(n *UploadedContent) { n.Edges.Contents = []*Content{} },
			func(n *UploadedContent, e *Content) { n.Edges.Contents = append(n.Edges.Contents, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ucq *UploadedContentQuery) loadContents(ctx context.Context, query *ContentQuery, nodes []*UploadedContent, init func(*UploadedContent), assign func(*UploadedContent, *Content)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*UploadedContent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(content.FieldUploadedContentFilename)
	}
	query.Where(predicate.Content(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(uploadedcontent.ContentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UploadedContentFilename
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "uploaded_content_filename" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ucq *UploadedContentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ucq.querySpec()
	_spec.Node.Columns = ucq.ctx.Fields
	if len(ucq.ctx.Fields) > 0 {
		_spec.Unique = ucq.ctx.Unique != nil && *ucq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ucq.driver, _spec)
}

func (ucq *UploadedContentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(uploadedcontent.Table, uploadedcontent.Columns, sqlgraph.NewFieldSpec(uploadedcontent.FieldID, field.TypeString))
	_spec.From = ucq.sql
	if unique := ucq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ucq.path != nil {
		_spec.Unique = true
	}
	if fields := ucq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadedcontent.FieldID)
		for i := range fields {
			if fields[i] != uploadedcontent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ucq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ucq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ucq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ucq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ucq *UploadedContentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ucq.driver.Dialect())
	t1 := builder.Table(uploadedcontent.Table)
	columns := ucq.ctx.Fields
	if len(columns) == 0 {
		columns = uploadedcontent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ucq.sql != nil {
		selector = ucq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ucq.ctx.Unique != nil && *ucq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ucq.predicates {
		p(selector)
	}
	for _, p := range ucq.order {
		p(selector)
	}
	if offset := ucq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ucq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UploadedContentGroupBy is the group-by builder for UploadedContent entities.
type UploadedContentGroupBy struct {
	selector
	build *UploadedContentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ucgb *UploadedContentGroupBy) Aggregate(fns ...AggregateFunc) *UploadedContentGroupBy {
	ucgb.fns = append(ucgb.fns, fns...)
	return ucgb
}

// Scan applies the selector query and scans the result into the given value.
func (ucgb *UploadedContentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ucgb.build.ctx, "GroupBy")
	if err := ucgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UploadedContentQuery, *UploadedContentGroupBy](ctx, ucgb.build, ucgb, ucgb.build.inters, v)
}

func (ucgb *UploadedContentGroupBy) sqlScan(ctx context.Context, root *UploadedContentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ucgb.fns))
	for _, fn := range ucgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ucgb.flds)+len(ucgb.fns))
		for _, f := range *ucgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ucgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UploadedContentSelect is the builder for selecting fields of UploadedContent entities.
type UploadedContentSelect struct {
	*UploadedContentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ucs *UploadedContentSelect) Aggregate(fns ...AggregateFunc) *UploadedContentSelect {
	ucs.fns = append(ucs.fns, fns...)
	return ucs
}

// Scan applies the selector query and scans the result into the given value.
func (ucs *UploadedContentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ucs.ctx, "Select")
	if err := ucs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UploadedContentQuery, *UploadedContentSelect](ctx, ucs.UploadedContentQuery, ucs, ucs.inters, v)
}

func (ucs *UploadedContentSelect) sqlScan(ctx context.Context, root *UploadedContentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ucs.fns))
	for _, fn := range ucs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ucs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
