// Code generated by ent, DO NOT EDIT.

package contentmoviemetadata

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ent-join/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldContainsFold(FieldID, id))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEQ(FieldHeight, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.FieldLTE(FieldHeight, v))
}

// HasContent applies the HasEdge predicate on the "content" edge.
func HasContent() predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ContentTable, ContentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentWith applies the HasEdge predicate on the "content" edge with a given conditions (other predicates).
func HasContentWith(preds ...predicate.Content) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(func(s *sql.Selector) {
		step := newContentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContentMovieMetadata) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContentMovieMetadata) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContentMovieMetadata) predicate.ContentMovieMetadata {
	return predicate.ContentMovieMetadata(sql.NotPredicates(p))
}
