// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Content is the predicate function for content builders.
type Content func(*sql.Selector)

// ContentMovieMetadata is the predicate function for contentmoviemetadata builders.
type ContentMovieMetadata func(*sql.Selector)

// UploadedContent is the predicate function for uploadedcontent builders.
type UploadedContent func(*sql.Selector)
